### ISSUE TITLE
Tuya Thermostat unavailable after setting temperature

### ISSUE THREAD

**Issue by hribaro1** [ollo69/ha_tuya_custom#49]
Tuya original and Tuya custom integration behave the same.
After reload of the hassio server temperature is shown on climate entity.

Besides wrong temperature showing which can be adjusted also setting of temperature does not work 
Switch on and switch off of the thermostat works normally.
If I want to set the temperature to different value then immediately thermostat becomes unavailable in hassio lovelace.

Thank you in advance for possible suggestions.
 
Regards
Robert

**Comment by myrulezzz** [comment]
Hi I am having the same issue. Able to switch on, switch off thermostat but changing the temperature makes thermostat unavailable in home assistant. 
After restarting home assistant it shows the correct status to off.
I am facing another one issue. Temperature is  shown:
21C is 2.1 in home assistant
I have tried adding in configuration.yaml
tuya_custom:
  devices_config:
    - device_name: <Friendly Name of your device in HA> # this is mandatory with at least one of the other keys
      unit_of_measurement: "C" # "F" or "C", not set to use value provided from cloud
      temp_divider: 1 # any positive number, all temperature values will be divided by this value
      curr_temp_divider: 1  # any positive number, only current temperature values will be divided by this value
      ext_temp_sensor: sensor.temp # a sensor that provide ambient temp used when not provided by device
but i get temperature instead of 21C,  210C

**Comment by Kirmas** [comment]
Its looks like https://github.com/PaulAnnekov/tuyaha/issues/51#issue-738530665

If this is a problem with out of range value you can change set_temperature function in the tuyaha/devices/climate.py file

def set_temperature(self, temperature):
        """Set new target temperature."""

        # the value used to set temperature is scaled based on the configured divider
        divider = self._divider or 1

        if not self.has_decimal():
            temp_val = round(float(temperature))
            set_val = temp_val * divider
        else:
            temp_val = float(temperature)
            set_val = round(temp_val * divider)
        if self._control_device("temperatureSet", {"value": temp_val}):
            self._update_data("temperature", set_val)

I think about pull request with this small fix but not sure that all devise work similar

**Comment by ollo69** [comment]
I have always wondered if the scaled temperature should be reset to the original value in the set method, but to maintain back compatibility and not having received any related issue until now, I set it as is.
As soon as I will have some time available, I will align this component to the version that will be released shortly in HA (PR is already merged), then I will proceed to define here a new parameter to manage this situation. If everything will be ok, I will proceed with the PRs in TuyaHA and HA. 
Just be patient, full process will take some times...

**Comment by ollo69** [comment]
Just released a new version to fix this issue.
There is a ne config option (Set Temperature value divided) that should be checked for this case.
Before pushing PR in TuyaHA and HA, please confirm this fix the issue.

**Comment by myrulezzz** [comment]
Hi ollo,
So you mean to updata tuya custom in my custom_components folder?

**Comment by ollo69** [comment]
Yes, please. You can also use HACS for this if you installed it.
Tuya Custom is intended to test new functionality for Tuya integration before pushing change in official library and integration, to speed-up test and avoid breaking change. Now this component is aligned again with last version of official HA integration and device configuration is managed from UI integration options.

**Comment by myrulezzz** [comment]
I have updated throw hacs.still when changing temp from ha the thermostat
goes to unavailable state and the temp instead for example 24 is 2.4

**Comment by ollo69** [comment]
Did you change some option in integration page?
Can you check HA logs for error message?

**Comment by myrulezzz** [comment]
Logger: custom_components.tuya_custom.tuyaha.tuyaapi
Source: custom_components/tuya_custom/tuyaha/tuyaapi.py:273
Integration: Tuya Custom (documentation
<https://www.home-assistant.io/integrations/tuya>)
First occurred: 19:21:01 (3 occurrences)
Last logged: 20:11:01
control device error, error code is ValueOutOfRange
This is the main error

**Comment by myrulezzz** [comment]
2020-12-08 20:08:41 WARNING (SyncWorker_12)
[custom_components.tuya_custom.tuyaha.tuyaapi] control device error, error
code is ValueOutOfRange
2020-12-08 20:11:01 WARNING (SyncWorker_10)
[custom_components.tuya_custom.tuyaha.tuyaapi] control device error, error
code is ValueOutOfRange

**Comment by ollo69** [comment]
Did you change some option in integration page?

**Comment by myrulezzz** [comment]
Hi,
Here are my options:

Because my thermostat was in program mode i have tried to chabge it to
manual and then went into ha and tried to change the temperature but still
the same.I don’t remember changing something in the integration page.If
there is something specific you want me to check let me know

**Comment by myrulezzz** [comment]
And thr temperature from 2.4 when i press the up arrow goes directly to 2.9 in the thermostat control.is this the correct behavior? Shouldn't go to 2.5 2.6 e.t.c?

**Comment by ollo69** [comment]
I don't see your options, I think you should post using browser and not e-mail.
Anyway, if I well understand, HA is showing values that is 1/10 of real one, eg 2.4 instead of 24.0, can you confirm this?
I need to do some modification, but than it will be required that you change options in HA for your device.
I'll let you know when new version will be available.

**Comment by myrulezzz** [comment]
![image](https://user-images.githubusercontent.com/43094013/101535208-fa310800-39a0-11eb-9c47-06501a779b8b.png)

Hi here are the options.yes you are correct for the temperature

**Comment by ollo69** [comment]
You should select your device from the list and select submit to configure it!

Please first of all install the last version I just released (v0.1.2) and then configure your device as in picture below:

![image](https://user-images.githubusercontent.com/60491700/101552729-a2e86300-39b3-11eb-8e47-53ea30934bc0.png)

Eventually define also minimum and maximum target values.

Than let me know if value are correct and set command works properly

**Comment by myrulezzz** [comment]
Ok after following the instructions:
On/off works fine.
Temperature instead of 240 shows as 2400.
When i press temperature from 2400 goes to 30 and nothing change on the
thermostat.then i press the down arrow changes to 29, goes to unavailable
and still get the same error.so basically the up arrow once takes you to
the correct maximum temperature and then arrow down gives you the same
error out of range.

**Comment by ollo69** [comment]
Sorry but your explanation is totally unclear and conflicting with previous information.
You said before that your thermostat was showing `2.4` instead of `24`, now you say `2400 `instead of `240`. Obviously if your thermostat in HA is displaying `240`, the `Temperature value divider` in the option page should be set to `10` and not `0.1`.
May be it is better if you post some images of what is really displayed in HA?

**Comment by myrulezzz** [comment]
General options
![options](https://user-images.githubusercontent.com/43094013/101623499-360bb200-3a21-11eb-93d6-b81d2371f009.JPG)

Thermostat Options
![thermostatoptions](https://user-images.githubusercontent.com/43094013/101623535-4459ce00-3a21-11eb-8b43-417e148db5cc.JPG)

Current Temperature shown on thermostat
![currentthermostat](https://user-images.githubusercontent.com/43094013/101623576-52a7ea00-3a21-11eb-8a97-9a413ab51b29.JPG)
Pressing the up arrow to increase temperature
![arrowup](https://user-images.githubusercontent.com/43094013/101623616-605d6f80-3a21-11eb-9508-a1d836136497.JPG)
Pressing the down arrow arrow to decrease temperature goes to 34 and then unavailable
![arrowdown](https://user-images.githubusercontent.com/43094013/101623662-75d29980-3a21-11eb-84ba-07319b6a51a7.jpg)

**Comment by ollo69** [comment]
Please set option `Temperature values divider` to `10` instead `0.1`
Report if it solve.

**Comment by myrulezzz** [comment]
Hi changed and the temperature is correct. But when changing temperature still goes to unavailable and get the same warning.

**Comment by ollo69** [comment]
Check option `Use Temperature value previously divided in set option`

**Comment by myrulezzz** [comment]
Hi now is working. Thank you very much.
I think you should add a note somewhere with this additional steps

**Comment by myrulezzz** [comment]
Ollo one more question. For tuya covers do you know any way to make the cover work with a slider? Instead of up down stop?

**Comment by ollo69** [comment]
Don't think it is possible, API do not provide information about current cover position.

**Comment by myrulezzz** [comment]
But i open a cover full the icon of the cover changes automatically to open.

**Comment by rhladky** [comment]
@ollo69  - I am too lazy to fiddle with custom component :) Any idea when the change will be available in official HA new version?

**Comment by ollo69** [comment]
Still need some adjustment and feed-back, than I will create PR but need commit from library and HA. It will take some times, may be 1 month...

**Comment by rhladky** [comment]
OK, I did setup the tuya custom integration and works like a hell :) Thank you very much for your effort @ollo69 . Wish you all the best and Merry Xmas.

**Comment by peetereczek** [comment]
I just changed from official integration to your custom one. Issue has gone, thanks for fix!
Looking forward for the merge information.

Correct setting example:
![image](https://user-images.githubusercontent.com/42431204/102779501-a0fba800-4394-11eb-86f0-e27eb1818c70.png)

**Comment by peetereczek** [comment]
But, I have noticed another strange behaviour @ollo69 

When I change the temperature, from detailed view of thermostat, all is fine.
![image](https://user-images.githubusercontent.com/42431204/102779858-3bf48200-4395-11eb-9f6f-adcd362a3cd7.png)

But when I do that from 'custom:simple-thermostat' card, the values after pressing '+' goes extreemely hight (doesn't pick divided values). There is no such issue with '-' action.

![image](https://user-images.githubusercontent.com/42431204/102779744-0f406a80-4395-11eb-8720-95eb55eebc33.png)
![image](https://user-images.githubusercontent.com/42431204/102779910-4dd62500-4395-11eb-8d4e-4a822f2f139b.png)

Also there is no issue with HA 'thermostat' card... I guess this custom-card issue?

**Comment by kitkat270** [comment]
Hi @ollo69, still not quite right for me I'm afraid.

Still getting these in the log, then the device goes unavailable.

`Logger: custom_components.tuya_custom.tuyaha.tuyaapi
Source: custom_components/tuya_custom/tuyaha/tuyaapi.py:273
Integration: Tuya Custom (documentation)
First occurred: 19:00:36 (4 occurrences)
Last logged: 19:08:04
control device error, error code is ValueOutOfRange`



![Screenshot 2021-01-12 at 19 14 02](https://user-images.githubusercontent.com/28577458/104361454-61932800-550a-11eb-82ee-4e2d49683a2e.png)

The temperature values are fine with the divider set at 10. But I'm getting the same 'unavailable' problem with and without the 'Use divider for set' ticked.

EDIT: Just to add... if I set the temp to 18, the display on the radiator shows 80.0. If I set it to 15, it shows 50.0. If I set it to 20, it shows 0.0. And it does this even when I untick the 'Use divider for set' box.


Many thanks for your efforts sorting all these things :-)

Amanda

**Comment by djp3k05** [comment]
thank you for your hard work. that fixed my issues and now my Moes thermostats are working fine. Temperature is displayed correctly and also I can set the desired target temperature.
Used the "10" divider value and the "Use divided temperature..." checkbox.
Unfortunately I discovered that sensors (like the sonoff zigbee temperature/pir and more) can't be imported from Tuya, as no support available for them. I will order the stuffs needed to use the zigbeemqtt to overcome all the issues with the Tuya integration.
Thank you again.

**Comment by thaliamontreux** [comment]
I'm having a issue with my thermostat from smart life I have a saswell thermostat. Hassio reports 45 degrees and im unable to adjust the tempature. here is what is interesting. When I add the thermostat to google, it creates 2 thermostats. But I only have one on smart life. One of them allows me to adjust the tempature and reports it correctly the other one just allows me to turn the power off to the device and reports 45 degrees... Why two thermostats. I looked in hassio and I only got one thermostat. So it's not correctly pulling information from tuya? can anyone help? This is very frustrating.

**Comment by ollo69** [comment]
This component is not supported anymore. Please refer to integration main page.

**Comment by myrulezzz** [comment]
Hi ollo,
My thermostats were working with tuya custom. After  uninstalling tuya
custom and installing tuya integration my thermostats have options only off
and auto and the temperature is wrong.

**Comment by diemon24** [comment]
> Общие опции ![Опции](https://user-images.githubusercontent.com/43094013/101623499-360bb200-3a21-11eb-93d6-b81d2371f009.JPG)
> 
> Варианты термостата ![термостатопции](https://user-images.githubusercontent.com/43094013/101623535-4459ce00-3a21-11eb-8b43-417e148db5cc.JPG)
> 
> Текущая температура, показанная на термостате ![текущийтермостат](https://user-images.githubusercontent.com/43094013/101623576-52a7ea00-3a21-11eb-8a97-9a413ab51b29.JPG)Нажатие стрелки вверх для повышения температуры ![стрелка вверх](https://user-images.githubusercontent.com/43094013/101623616-605d6f80-3a21-11eb-9508-a1d836136497.JPG)Нажатие стрелки вниз для снижения температуры доходит до 34, а затем недоступно ![стрелка вниз](https://user-images.githubusercontent.com/43094013/101623662-75d29980-3a21-11eb-84ba-07319b6a51a7.jpg)

Hello. After install custom Tuya and activated integration, after more times (many hours) I see all devices in HA. But configuration page in Tuya Custom integration not open. When I can click "Configuration" I see window "Don't open configuration". How config file I can enter parameters thermostats parameters (values devider)?  

in /config/custom_components/tuya_custom/tuyaha/devices/climate.py I change this param:

string 19-24 I change devider 1 to 10:
    def __init__(self, data, api):
        super().__init__(data, api)
        self._unit = None
        self._divider = **10**
        self._divider_set = False
        self._ct_divider = **10**

and my temperature now correct in Lovelace
